services:
  - type: web
    name: roof-api
    env: docker
    plan: free
    rootDir: api
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: AUTO_CREATE_TABLES
        value: "true"
      - key: OPENSEARCH_URL
        value: "http://opensearch-disabled.local"
      - key: REDIS_URL
        value: "redis://redis-disabled.local/0"
    databases:
      - name: roof-postgres

databases:
  - name: roof-postgres
    plan: free

